### ISSUE TITLE
Negative values with CurrencyInputFormatter

### ISSUE THREAD

**Issue by rivella50** [caseyryan/flutter_multi_formatter#123] opened 2023-04-04 18:57 UTC
I use the CurrencyInputFormatter for formatting entered money values. So far these were only positive ones.
Now the customer also wants to support negative values. Is this somehow possible to accomplish?
This is the code i use at the moment for positive values:
```
TextFormField(
  initialValue: toCurrencyString(
    value.toStringAsFixed(2),
    leadingSymbol: currencySymbol,
    useSymbolPadding: true,
  ),
  keyboardType: const TextInputType.numberWithOptions(
    decimal: true,
    signed: true,
  ),
  textInputAction: TextInputAction.done,
  inputFormatters: [
    CurrencyInputFormatter(
      leadingSymbol: currencySymbol,
      useSymbolPadding: true,
      onValueChange: (num newValue) => onInputChange(newValue.toStringAsFixed(2))
    )
  ],
)
```
![Screenshot 2023-04-04 at 20 58 05](https://user-images.githubusercontent.com/54292/229893135-be7b7b9b-0a62-4193-a344-ff34216a3af6.png)

**Comment by caseyryan** [comment] 2023-04-13 05:33
So, what's the problem with negative ones?

**Comment by rivella50** [comment] 2023-04-13 05:37
Whenever i tap the minus key it's not displayed and the caret moves one step to the right.
Did you use my code above for testing?

**Comment by caseyryan** [comment] 2023-04-13 05:44
I also tried to add a useSymbolPadding: true and it really works a bit strange but it still allows minus 
![Screenshot at Apr 13 12-43-20](https://user-images.githubusercontent.com/4113558/231664393-46bd4ce4-95a1-4023-9029-38e83907ef06.png)

**Comment by caseyryan** [comment] 2023-04-20 04:39
> 
I believe it's somehow related to your code. Maybe the problem is related to this 
```onValueChange: (num newValue) => onInputChange(newValue.toStringAsFixed(2))```
and setting the initialValue. 
I don't see the rest of the code but I can assure you it works fine in mine

**Comment by rivella50** [comment] 2023-04-25 09:56
Ok it works somehow, but it still behaves a little bit strange:
The `initialValue` is always positive in the code of my initial post, so there is no problem arising.

But here is the strange part:
1) I enter the negative sign and it is shown and passed correctly by `onValueChange`:
![Screenshot 2023-04-25 at 11 45 50](https://user-images.githubusercontent.com/54292/234239474-f1a2316d-0d8d-46c8-9d47-4cc87f192cf5.png)
received -94.65

2) Now i enter an additional int: The negative sign vanishes but `onValueChange` still sends the new negative value:
![Screenshot 2023-04-25 at 11 47 23](https://user-images.githubusercontent.com/54292/234239926-93bf7fe0-7e55-47b3-95c6-b6748a5d474b.png)
received -494.65

3) Only when i add or remove another digit the value and sent value in `onValueChange` do correspond:
![Screenshot 2023-04-25 at 11 49 03](https://user-images.githubusercontent.com/54292/234240308-ba0aebbe-b92a-4eef-b07b-3451bd75670c.png)
received 49.65

So in my opinion there is a problem in 2) when trying to change the value if the negative sign has already been applied.

Another problem seems to be that the formatter seems to interpret the negative sign as a valid digit, i.e. it shows the thousands separator for a value which doesn't need it:
![Screenshot 2023-04-25 at 11 52 50](https://user-images.githubusercontent.com/54292/234241509-56b4187e-a8a1-41cd-95b5-03903fd1e9ea.png)

The code for the used TextFormField is still the same as in my initial post.

**Comment by rivella50** [comment] 2023-04-25 13:05
EDIT: I'm sorry, i was on an older version of this plugin. Everything seems to work correctly with the most recent version, except that it's still showing the thousands separator if the minus sign is put directly in front of the first digit:
![Screenshot 2023-04-25 at 15 03 28](https://user-images.githubusercontent.com/54292/234284941-8ebff30e-ad89-48f7-97f5-548eba2fbd7f.png)

Also it allows having 2 minus signs (which doesn't change the sign of the final value but it looks weird):
![Screenshot 2023-04-25 at 15 04 39](https://user-images.githubusercontent.com/54292/234285214-14d6edd0-fcc3-428b-89ac-942416d972cd.png)

**Comment by caseyryan** [comment] 2023-04-26 16:34
Yes, that is weird. I’ll take a look at this as soon as I have time

**Comment by caseyryan** [comment] 2023-05-08 06:09
Fixed with a hack. It might potentially cause some problem in other places though. Didn't have time to test thoroughly

**Closed by caseyryan** 2023-05-08 06:09 UTC
