### ISSUE TITLE
Zeros ignored in MoneyInputFormatter

### ISSUE THREAD

**Issue by Prn-Ice** [caseyryan/flutter_multi_formatter#12] opened 2020-07-23 15:19 UTC
![Peek 2020-07-23 16-14](https://user-images.githubusercontent.com/48252841/88304176-d75acb80-ccff-11ea-99e6-17be2b90f7bd.gif)
`mantissaLength: 0` fixes this.

**Comment by caseyryan** [comment] 2020-07-24 09:08
thanks for your feedback. I'll take a look into it

**Comment by caseyryan** [comment] 2020-11-16 02:58
fixed in version 1.2.0

**Closed by caseyryan** 2020-11-16 02:58 UTC

**Comment by rcsousa14** [comment] 2022-05-25 15:25
Still having this issue!

**Comment by caseyryan** [comment] 2022-05-25 15:45
> Still having this issue! v2.5.7

Can you provide an example to reproduce this?

**Comment by rcsousa14** [comment] 2022-05-25 15:49
> > Still having this issue! v2.5.7
> 
> Can you provide an example to reproduce this?

I have Created a textField with the 
```
MoneyInputFormatter(
            trailingSymbol: "AOA",
            useSymbolPadding: true,
            mantissaLength: 2 
        )
```
every time I try to type 1.000.000,00 AOA it just sets it to 10,00 AOA for some reason

**Comment by caseyryan** [comment] 2022-05-25 15:54
> > > Still having this issue! v2.5.7
> > 
> > 
> > Can you provide an example to reproduce this?
> 
> I have Created a textField with the
> 
> ```
> MoneyInputFormatter(
>             trailingSymbol: "AOA",
>             useSymbolPadding: true,
>             mantissaLength: 2 
> 
>         )
> ```
> 
> every time I try to type 1.000.000,00 AOA it just sets it to 10,00 AOA for some reason

Will it work if you use leading symbol instead of trailing? Just to check it. I think the reason why it happens is incorrect calculation caret position which requires a leading symbol

**Comment by rcsousa14** [comment] 2022-05-25 15:57
okay yea it works. Thank you! but I should be able to use the trailing too..no?

**Comment by caseyryan** [comment] 2022-05-25 16:19
It definitely is a bug. I'll try to find out what's happening there as soon as I can
