### ISSUE TITLE
Using onValueChange, if you submit the number after pressing ".", it adds two 0s to the number before the "."

### ISSUE THREAD

**Issue by pedez** [caseyryan/flutter_multi_formatter#16] opened 2020-10-23 19:43 UTC
Maybe this only happens in my specific case. If it wasn't clear in the title here is a more detailed explanation:

On an app I'm creating, the user inputs a number (like € 20.00). If that user only taps the "2" + "0", the number will be "€ 20.00" which works. 

And if the user submits (I'm saving the onValueChange to a variable, and then the submit button calls a function that uses that variable to store it on the UI) that, it will work. 

However, if the user taps the "2" + "0" and then the ".", the displayed number on the UI textfield is still "€ 20.00". HOWEVER, if you submit after that (after tapping the "."), the number will be stored as "2000.00". 

Very strange, I wish I knew how to fix it but I'm quite a noob, to be honest. Dart is the language I know best and I don't know that much, this is my first app. Let me know if you need any more info, love this package!

**Comment by pedez** [comment] 2020-10-23 20:05
![bugex](https://user-images.githubusercontent.com/58760325/97049319-726b7780-1573-11eb-8984-3418c1d67ac1.gif)

**Comment by caseyryan** [comment] 2020-11-06 05:26
Hi! To your example, it's not really related to the package. It seems like you apply some more formatting but I'm not sure what exactly. Could you, please, share some working example where this bug can be reproduced?

**Comment by pedez** [comment] 2020-11-08 14:03
Oh, it's not related to the package? Sorry then haha. 

Yes, of course. I created a small project to show this off. https://github.com/pedez/ExamplePackageApp
(The relevant file is here: https://github.com/pedez/ExamplePackageApp/blob/master/lib/package.dart)

Here is the problem happening on this project:
https://im7.ezgif.com/tmp/ezgif-7-9fe4a3576c8f.gif

**Comment by pedez** [comment] 2020-11-08 14:06
[https://im7.ezgif.com/tmp/ezgif-7-9fe4a3576c8f.gif](url)

**Comment by pedez** [comment] 2020-11-08 14:07
Oops, that was accidental.

**Comment by caseyryan** [comment] 2020-11-08 14:22
Thanks! I'll take a look at this tomorrow. I planned to publish an upgrade today but I couldn't, so most probably I will also fix this bug (if it turns out to be the package related)

**Comment by pedez** [comment] 2020-11-08 16:58
Awesome! Again, thanks a lot for this package, you must be an amazing programmer!

**Comment by caseyryan** [comment] 2020-11-16 02:45
Updated the package. Now the formatting logic is totally different. I do not have an issue like this now. If you can check it with your code it would be awesome. Important notice: it now demands Flutter 1.22.4 because 1.22.2 had a big issue with base TextInputFormatter which (most probably) caused a similar behavior. The reason was that a newValue was always the same despite what a formatting method has returned. They fixed it now. 
I'll close the issue but if you still can reproduce a bug like this feel free to reopen it

**Closed by caseyryan** 2020-11-16 02:45 UTC
