### ISSUE TITLE
Unfocuser has a bug: recklicking in an already focused text field.

### ISSUE THREAD

**Issue by Wissperwind** [caseyryan/flutter_multi_formatter#51] opened 2021-06-07 15:01 UTC
Hi,

I tried to use your unfocouser for a website.
If I click into a text filed. It get's focused. If I click into a white area next to it, it get's unfocused.
But If I click again into a already focused textfield, it get's also unfocused. User did not expect that.
Example use case:
Open the website, oh, I need to copy and paste something in this text field. Click in it.
Switch the window and copy something. Return and click again into the already selected text field.
Press Ctrl V.
Nothing get's pasted because the text field is now defocused.

**Comment by caseyryan** [comment] 2021-06-10 07:23
Thats weird. I'll take a look at this when I have time. Thanks for reporting

**Comment by caseyryan** [comment] 2021-06-10 13:56
I've just tested it everywhere. In mobile and web. I did it exactly as you described. I 100% there is no bug like this. Everything works correctly. 
What version of flutter do you use? Can you also provide some example code of the page I can reproduce the bug?

**Comment by caseyryan** [comment] 2021-06-12 05:03
I'm closing the issue now as I could not reproduce it

**Closed by caseyryan** 2021-06-12 05:03 UTC

**Comment by Wissperwind** [comment] 2021-06-15 09:18
They fiexed it in flutter. So no need for this unfocuser anymore. Problem solved :)

**Comment by caseyryan** [comment] 2021-06-15 09:33
Unfocuser is used for different purposes. I'm glad the problem is resolved
