### ISSUE TITLE
Phone format while typing doesn't work Flutter stable 2.0.1

### ISSUE THREAD

**Issue by sgehrman** [caseyryan/flutter_multi_formatter#34] opened 2021-03-08 00:35 UTC
Just got the flutter stable branch 2.0.1.  The example app doesn't work for phone format while typing.  Try to get the flutter team to merge the fix into  stable.

**Comment by sgehrman** [comment] 2021-03-08 00:36
https://github.com/flutter/flutter/pull/75541

**Comment by caseyryan** [comment] 2021-03-08 04:42
I have no contacts with Flutter team, so I can't influence them in any way :) 
I'll take a look at this issue with Flutter 2.x.x but I'm not sure if I'll be able to fix it. This is not the first time they introduce this bug btw

**Comment by caseyryan** [comment] 2021-03-13 05:09
I've just checked it with Flutter 2.0.2 stable and it works just fine. So I'm closing this

**Closed** 2021-03-13 05:10 UTC

**Comment by SungHyun-Patrick-Lee** [comment] 2021-03-15 06:41
I upgrade flutter version to 2.0.2 (stable)
But still get same issue 
I think open this issue again

**Comment by caseyryan** [comment] 2021-03-15 06:57
I tested my example project and I can testify there is no such issue with Flutter 2.0.2. Phone formats just fine. 
Could you tell me what phone number you enter to reproduce this? Can it be because there is just no mask for it? 
Try this with some phone like 79998886655 and see if it will format

**Comment by SungHyun-Patrick-Lee** [comment] 2021-03-16 04:46
> SungHyun-Patrick-Lee, I tested my example project and I can testify there is no such issue with Flutter 2.0.2. Phone formats just fine.
> Could you tell me what phone number you enter to reproduce this? Can it be because there is just no mask for it?
> Try this with some phone like 79998886655 and see if it will format. I personally use my package for all of my work projects and phones get formatted everywhere, no issues with that

I tested it using 01012345678. It's a confirmation message that works fine on IOS. On Android I still have that problem.

**Comment by caseyryan** [comment] 2021-03-16 04:50
> > SungHyun-Patrick-Lee, I tested my example project and I can testify there is no such issue with Flutter 2.0.2. Phone formats just fine.
> > Could you tell me what phone number you enter to reproduce this? Can it be because there is just no mask for it?
> > Try this with some phone like 79998886655 and see if it will format. I personally use my package for all of my work projects and phones get formatted everywhere, no issues with that
> 
> I tested it using 01012345678. It's a confirmation message that works fine on IOS. On Android I still have that problem.

There is no country code starting with 0 thus there is no mask supporting it. All phone numbers MUST start with a valid country code

**Comment by SungHyun-Patrick-Lee** [comment] 2021-03-17 01:16
> > > SungHyun-Patrick-Lee, I tested my example project and I can testify there is no such issue with Flutter 2.0.2. Phone formats just fine.
> > > Could you tell me what phone number you enter to reproduce this? Can it be because there is just no mask for it?
> > > Try this with some phone like 79998886655 and see if it will format. I personally use my package for all of my work projects and phones get formatted everywhere, no issues with that
> > 
> > 
> > I tested it using 01012345678. It's a confirmation message that works fine on IOS. On Android I still have that problem.
> 
> There is no country code starting with 0 thus there is no mask supporting it. All phone numbers MUST start with a valid country dial code. 0 is used as a masking symbol, so there is no way to add a phone starting with 0
> 
> > > that works fine on IOS
> 
> It's absolutely impossible. The package does not use any platform dependent code. It is completely written in dart. iOS version works exactly the same as Android

It seems to be my mistake. Thank you for your sincere response. Have a nice day :)
