### ISSUE TITLE
Paste value in empty field fails on CurrencyInputFormatter.formatEditUpdate

### ISSUE THREAD

**Issue by RomanovaPrime** [caseyryan/flutter_multi_formatter#124] opened 2023-04-20 14:52 UTC
When try to paste a valid value (sutch as 12.34) in empty TextField, formatEditUpdate returns the old value.

old value: 
TextEditingValue(text: ┤├, selection: TextSelection.collapsed(offset: 0, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))

pasted value: 
TextEditingValue(text: ┤52.74├, selection: TextSelection.collapsed(offset: 5, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))

returned formated value: 
TextEditingValue(text: ┤├, selection: TextSelection.collapsed(offset: 0, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))

Currently we use work around: 
oldValue = oldValue.text == ''
    ? const TextEditingValue(text: '0.00', selection: TextSelection.collapsed(offset: 4), )
    : oldValue;

**Comment by caseyryan** [comment] 2023-04-26 16:37
Can you provide a code snippet which reproduces this?
Also I need to know the version of the package you use and your version of flutter

**Comment by RomanovaPrime** [comment] 2023-04-27 05:55
Hi, 
the package version is:
  flutter_multi_formatter: ^2.5.1

 flutter --version
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (9 days ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

Here is the function, I use:

 formatEditUpdate(oldValue, newValue);

**Comment by rivella50** [comment] 2023-04-27 19:13
@RomanovaPrime Why do you use such an old version of this package?
The current version is 2.10.2 and perhaps your problem already has been fixed in one of the released updates.

**Comment by caseyryan** [comment] 2023-04-28 01:21
> Hi, the package version is: flutter_multi_formatter: ^2.5.1
> 
> flutter --version Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git Framework • revision 4d9e56e694 (9 days ago) • 2023-04-17 21:47:46 -0400 Engine • revision 1a65d409c7 Tools • Dart 2.19.6 • DevTools 2.20.1
> 
> Here is the function, I use:
> 
> formatEditUpdate(oldValue, newValue);

1) Your version of the package is too old. There was a lot of changes since that version 
2) You’re using it incorrectly. The method you have mentioned must not be used manually, it is called automatically when you add a CurrencyInputFormatter into the “inputFormatters” list of your text field. 
If you need to format a string, you should use one of the utility methods. Please read the package description 

I’ll close this thread for now because there is nothing to fix

**Closed by caseyryan** 2023-04-28 01:21 UTC
